### ISSUE TITLE
Create a user and developer package

### ISSUE THREAD

**Issue by brianmoose** [idaholab/package_builder#101]
The user package should contain essentially what is in the current package. We could possibly reduce some of the PETSc versions, SLEPc, etc but that can wait.

The developer package would contain what is in the user package plus a stack based on the minimum required compiler versions (ie gcc 4.8 and whatever our minimum clang version is). This package would allow CIVET (and developers) to test our minimum requirements.

@permcody and @aeslaughter  anything to add?

**Comment by milljm** [comment]
Done
