### ISSUE TITLE
Build LLVM with RTTI enabled

### ISSUE THREAD

**Issue by dschwen** [idaholab/package_builder#114]
It seems that by default LLVM is build with `-fno-rtti`. This means when building code that links to the LLVM libs no RTTI can be used (i.e. no `dynamic_cast`). That's bad (we use it all over the place in MOOSE).

**Comment by dschwen** [comment]
*) Run-time type info

**Comment by dschwen** [comment]
See https://llvm.org/docs/Packaging.html 

> LLVM disables RTTI by default. Add `REQUIRES_RTTI=1` to your environment while running make to re-enable it. This will allow users to build with RTTI enabled and still inherit from LLVM classes.

**Comment by milljm** [comment]
Saw that... also I am going to do:


```pre
-DLLVM_ENABLE_RTTI=ON \
```
According to a few sites I found...
