### ISSUE TITLE
Valgrind not working in OS 10.12 (Sierra)

### ISSUE THREAD

**Issue by permcody** [idaholab/package_builder#116]
Valgrind appears to work when I installed it through home brew, but the version included in this package doesn't work. I'm not sure if we want to necessarily build it or not if we can just brew install it. In either case the broken version should be removed.

**Comment by milljm** [comment]
This is supposedly in the next rendition of our package. I just forgot to link this issue.
#115

**Comment by milljm** [comment]
#115 was merged. And so this issue should be resolved.
