### ISSUE TITLE
Convenience link for current clang-format script

### ISSUE THREAD

**Issue by permcody** [idaholab/package_builder#152]
I have a line in my emacs file that points to the clang-format script in the package:
```
/opt/moose/llvm-<version>/share/clang/clang-format.el
```

The problem I have is that every time I get a new package, I have to update this line in my `.emacs` file. It would be handy to have a soft link that points to the current version when a new package is built.

**Comment by milljm** [comment]
@permcody Done.
The link will exist at:

```
  /opt/moose/clang-format.el
```
